platform :ios, '7.0'
pod 'Download-Font-iOS', :path => 'https://github.com/hisa0507/Download-Font-iOS.git'

target 'Download-Font-iOS', :exclusive => true do
  pod "Download-Font-iOS", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Download-Font-iOS", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
